language: cpp

compiler: gcc

before_install:
 - uname -a
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake sqlite3 libsqlite3-dev qt5-default qtbase5-dev-tools cscope exuberant-ctags libqt5scintilla2-dev rpm

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make package

after_script:
  - sudo make install
  - cqmakedb -v
  - cd ..
  - cscope -cbR
  - ctags --fields=+i -nR
  - cqmakedb -s cq.db -c cscope.out -t tags -p -d
  - cqsearch -s cq.db -p 1 -t CODEQUERY_SW_VERSION

notifications:
  email:
    - ruben2020-git@users.sourceforge.net
  on_success: change
  on_failure: always


